{% set name = "dmri-dicelib" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8c458870d0367c193af83cca69eef029710d4c1e686ec6930c760c6c076f4cb2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
  run:
    - cython
    - h5py >=3
    - nibabel
    - psutil
    - python
    - pywin32  # [win]
    - scipy

test:
  imports:
    - dicelib

about:
  home: https://pypi.org/project/dmri-dicelib/
  license: LicenseRef-DICE-lab
  license_file: LICENSE
  summary: Various algorithms developed by the DICE lab to process/manipulate diffusion MRI objects, e.g. streamlines, tractograms etc.
  dev_url: https://pypi.org/project/dmri-dicelib/

extra:
  recipe-maintainers:
    - daducci
    - nightwnvol
    - pauldmccarthy
