{% set name = "dmri-dicelib" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff34b5330888d25ac430764d1801ee00ebe2a72b52b2a814e052112790bfdbac

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - dipy
    - h5py >=3
    - {{ pin_compatible('numpy') }}
    - python
    - scipy

test:
  imports:
    - dicelib

about:
  home: https://pypi.org/project/dmri-dicelib/
  license: LicenseRef-DICE-lab
  license_file: LICENSE
  summary: Various algorithms developed by the DICE lab to process/manipulate diffusion MRI objects, e.g. streamlines, tractograms etc.
  dev_url: https://pypi.org/project/dmri-dicelib/

extra:
  recipe-maintainers:
    - daducci
    - nightwnvol
    - pauldmccarthy
